[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (React builds to 'build' folder)
  publish = "build"
  
  # Environment variables for build process
  environment = { CI = "false", GENERATE_SOURCEMAP = "false", ESLINT_NO_DEV_ERRORS = "true" }

# Redirects and rewrites for Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for shorter time
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache CSS and JS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration (if you have serverless functions)
[functions]
  # Directory where your functions are stored
  directory = "netlify/functions"
  
  # Node.js version for functions
  node_bundler = "esbuild"

# Development settings
[dev]
  command = "npm start"
  port = 3000
  publish = "build"
  autoLaunch = false

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugin configuration
[[plugins]]
  package = "netlify-plugin-lighthouse"
  
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
    
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Context-specific settings
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production", CI = "false" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production", CI = "false" }

[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "production", CI = "false" }

# Development context
[context.dev]
  environment = { NODE_ENV = "development" }